<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="test.aspx.cs" Inherits="myproject.login" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateSelectButton="True" DataSourceID="SqlDataSource1" AllowPaging="True" BackColor="White" BorderColor="White" BorderStyle="Ridge" BorderWidth="2px" CellPadding="3" CellSpacing="1" GridLines="None" Width="485px">
            <Columns>
                <asp:BoundField DataField="job_title" HeaderText="job_title" SortExpression="job_title" />
                <asp:BoundField DataField="job_desc" HeaderText="job_desc" SortExpression="job_desc" />
                <asp:BoundField DataField="job_functional_area" HeaderText="job_functional_area" SortExpression="job_functional_area" />
                <asp:BoundField DataField="job_sort" HeaderText="job_sort" SortExpression="job_sort" />
                <asp:TemplateField>
                    <ItemTemplate>
                        <asp:HyperLink ID="HyperLink1" NavigateUrl="~/WebForm1.aspx" runat="server">HyperLink</asp:HyperLink>
                    </ItemTemplate>
                </asp:TemplateField>
                
            
            </Columns>
          
            <FooterStyle BackColor="#C6C3C6" ForeColor="Black" />
            <HeaderStyle BackColor="#4A3C8C" Font-Bold="True" ForeColor="#E7E7FF" />
            <PagerStyle BackColor="#C6C3C6" ForeColor="Black" HorizontalAlign="Right" />
            <RowStyle BackColor="#DEDFDE" ForeColor="Black" />
            <SelectedRowStyle BackColor="#9471DE" Font-Bold="True" ForeColor="White" />
            <SortedAscendingCellStyle BackColor="#F1F1F1" />
            <SortedAscendingHeaderStyle BackColor="#594B9C" />
            <SortedDescendingCellStyle BackColor="#CAC9C9" />
            <SortedDescendingHeaderStyle BackColor="#33276A" />
        </asp:GridView>
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:jobportaldb %>" SelectCommand="SELECT [job_title], [job_desc], [job_functional_area], [job_sort] FROM [job_title_tbl]"></asp:SqlDataSource>
    <div>
    
    </div>
       
      
    </form>
</body>
</html>
